#!/usr/bin/env bash
# Build attachment tarballs for the upstream issue drafts.
#
# Outputs to scripts/repros/dist/ (gitignored). Two tarballs:
#
#   elicit-als-context-minimal.tar.gz
#     The minimal McpAgent + Worker Loader child harness. Smallest
#     possible repro of the agentContext ALS gap. Attach to the ALS
#     issue.
#
#   elicit-als-context-codemode-pattern.tar.gz
#     The scaffold-shaped harness. Reproduces both the ALS gap and
#     the AJV-validator-default gap; controlled by env-var toggles
#     (WRAP, TRIGGER_VALIDATION, VALIDATOR). Attach to either issue;
#     the validator issue cares more about it.
#
# Usage: bash scripts/repros/make-tarballs.sh [output_dir]
#   default output_dir: scripts/repros/dist/

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT_DIR="${1:-${REPO_ROOT}/scripts/repros/dist}"
SRC_BASE="${REPO_ROOT}/scripts/repros/elicit-als-context"

mkdir -p "$OUT_DIR"

# Files/dirs to exclude from each tarball:
#   node_modules/        — install-time, regenerated by `pnpm install`
#   .wrangler/           — runtime cache from `wrangler dev`
#   pnpm-lock.yaml       — pnpm resolver state; reproducer can resolve fresh
EXCLUDES=(
  --exclude='node_modules'
  --exclude='.wrangler'
  --exclude='pnpm-lock.yaml'
)

build_tarball() {
  local name="$1"
  local src="$2"
  local dst="${OUT_DIR}/elicit-als-context-${name}.tar.gz"

  if [ ! -d "$src" ]; then
    echo "ERROR: source directory not found: $src" >&2
    return 1
  fi

  # tar from REPO_ROOT so paths in the archive are stable
  # (elicit-als-context/<name>/...)
  tar czf "$dst" \
    -C "$REPO_ROOT/scripts/repros" \
    "${EXCLUDES[@]}" \
    "elicit-als-context/${name}"

  local size
  size=$(stat -c%s "$dst" 2>/dev/null || stat -f%z "$dst")
  printf "  built %-50s %d bytes\n" "$dst" "$size"
}

echo "Building repro tarballs to: $OUT_DIR"
build_tarball "minimal"   "$SRC_BASE/minimal"
build_tarball "codemode-pattern" "$SRC_BASE/codemode-pattern"
echo "Done."
