import type { SurfaceReview } from "@local/shared";
import { inspectFilterCreate } from "./inspectors/filters.js";
import { inspectOutboundMessage, inspectDraftSend } from "./inspectors/outbound.js";
import { normalizeOutboundMessage } from "./inspectors/normalize-subject.js";
// NB: `inspectSendAsCreate` (./inspectors/sendas.js) is deliberately NOT
// imported — sendAs.create is denied outright, and a static deny short-circuits
// before `inspect` is read. The inspector is retained as the reference
// implementation and is exercised directly by its own tests; see the
// re-enablement path in that entry's `reasoning`.
import { inspectEventAttendees } from "./inspectors/calendar-attendees.js";

// ---------------------------------------------------------------------------
// clientNote prose. Client-visible, aimed at the model, and appended to the
// operation's spec description by annotateSpecWithSurfaceReview — so `search`
// states the request-time condition where it is relevant. Each note describes
// what its inspector ACTUALLY does; keep them in step with the code in
// ./inspectors/. Structural facts ("allowed but inspected", "needs approval")
// are generated by the annotator and are deliberately not repeated here.
// ---------------------------------------------------------------------------

/** inspectEventAttendees — shared by events.insert/update/patch/import. */
const ATTENDEE_ALLOWLIST_CLAUSE =
  "Every attendee must be on the outbound allowlist " +
  "(OUTBOUND_RECIPIENT_ALLOWLIST; unset means an empty list, so any attendee " +
  "at all is denied). One off-allowlist attendee denies the whole write " +
  "outright — a hard deny, not an approval prompt. Only Google rooms/equipment " +
  "(`resource: true` at resource.calendar.google.com) are exempt. Send the " +
  "event as a JSON object in `body`; any other payload is denied.";

const ATTENDEE_NOTE =
  ATTENDEE_ALLOWLIST_CLAUSE +
  " More than 25 attendees, counted after de-duplication, needs interactive " +
  "approval instead. A body with no `attendees` array is unaffected.";

/** events.import is STATICALLY elicit, so approval is always required and no
 *  request "just works". The shared note's "needs approval instead" and "no
 *  attendees is unaffected" clauses would contradict that generated prefix. */
const ATTENDEE_NOTE_IMPORT =
  ATTENDEE_ALLOWLIST_CLAUSE +
  " The attendee check runs before approval is sought, so an off-allowlist " +
  "attendee denies the import without reaching it.";

export const surfaceReview: SurfaceReview = {
  // === Tier 1: allow in slice 1 ===
  "gmail.users.getProfile":                { decision: "allow", category: "standard_read" },
  "gmail.users.labels.list":               { decision: "allow", category: "standard_read" },
  "gmail.users.labels.get":                { decision: "allow", category: "standard_read" },
  "gmail.users.labels.create":             { decision: "allow", category: "standard_write" },
  "gmail.users.labels.update":             { decision: "allow", category: "standard_write" },
  "gmail.users.labels.patch":              { decision: "allow", category: "standard_write" },
  "gmail.users.labels.delete":             { decision: "allow", category: "standard_write" },
  "gmail.users.messages.list":             { decision: "allow", category: "standard_read" },
  "gmail.users.messages.get":              { decision: "allow", category: "standard_read" },
  "gmail.users.messages.modify":           { decision: "allow", category: "standard_write",
                                              reasoning: "Body-level inspection considered and rejected — auto-archive via removeLabelIds: [INBOX] is a common legitimate use case; reviewer should not assume the lack of inspector is an oversight." },
  "gmail.users.messages.batchModify":      { decision: "allow", category: "standard_write",
                                              reasoning: "Body-level inspection considered and rejected — auto-archive via removeLabelIds: [INBOX] is a common legitimate use case; reviewer should not assume the lack of inspector is an oversight." },
  "gmail.users.messages.trash":            { decision: "allow", category: "standard_write" },
  "gmail.users.messages.untrash":          { decision: "allow", category: "standard_write" },
  "gmail.users.threads.list":              { decision: "allow", category: "standard_read" },
  "gmail.users.threads.get":               { decision: "allow", category: "standard_read" },
  "gmail.users.threads.modify":            { decision: "allow", category: "standard_write" },
  "gmail.users.threads.trash":             { decision: "allow", category: "standard_write" },
  "gmail.users.threads.untrash":           { decision: "allow", category: "standard_write" },
  "gmail.users.drafts.list":               { decision: "allow", category: "standard_read" },
  "gmail.users.drafts.get":                { decision: "allow", category: "standard_read" },
  "gmail.users.drafts.create":             { decision: "allow", category: "standard_write", normalizeBody: normalizeOutboundMessage,
                                              reasoning: "Deliberately uninspected: a draft is inert until sent, so it may address any recipient (or none at all mid-composition). The outbound allowlist is enforced at send time — messages.send and drafts.send both carry recipients through inspectOutboundMessage. Subject normalization still applies (a stored draft can be sent later from the Gmail UI, bypassing our send path)." },
  "gmail.users.drafts.update":             { decision: "allow", category: "standard_write", normalizeBody: normalizeOutboundMessage,
                                              reasoning: "Deliberately uninspected, same rationale as drafts.create: recipient gating happens at send time, not draft time." },
  "gmail.users.drafts.delete":             { decision: "allow", category: "standard_write" },

  // === Slice-2 closeout additions ===
  "gmail.users.settings.filters.list":     { decision: "allow", category: "standard_read" },
  "gmail.users.settings.filters.get":      { decision: "allow", category: "standard_read" },
  "gmail.users.messages.attachments.get":  { decision: "allow", category: "standard_read" },

  // === Tier 2: outbound + irreversible. Sends are inspected; remaining elicit ops enforce as deny in slice 1. ===
  "gmail.users.messages.send":             { decision: "allow", inspect: inspectOutboundMessage, normalizeBody: normalizeOutboundMessage,
                                              clientNote:
                                                "Every To/Cc/Bcc recipient must be on this deployment's outbound " +
                                                "allowlist (the OUTBOUND_RECIPIENT_ALLOWLIST var; unset means an empty " +
                                                "list, so every send is denied). One off-allowlist address denies the " +
                                                "send. Recipients are read from `raw` or `payload.headers` (or the " +
                                                "uploaded RFC 822 message for a media/multipart upload); a payload " +
                                                "with no readable recipients is denied. Write each recipient as a bare " +
                                                "addr@host or Name <addr@host>: quoted names, comments and names " +
                                                "holding @ : ; , [ ] \\ are denied even for allowlisted addresses. " +
                                                "More than 25 recipients needs interactive approval instead." },
  "gmail.users.drafts.send":               { decision: "allow", inspect: inspectDraftSend, normalizeBody: normalizeOutboundMessage,
                                              reasoning: "Drafts are created/updated ungated, so a stored draft's recipients are unvetted. inspectDraftSend denies a bare send-by-id (a synchronous inspector cannot read the stored draft to verify its recipients) and delegates update-and-send ({id, message}) to inspectOutboundMessage, whose carried recipients are what Gmail actually sends to.",
                                              clientNote:
                                                "Sending by id alone is always denied: drafts are created and updated " +
                                                "without recipient checks, and the stored draft cannot be read at send " +
                                                "time. Send it as an update-and-send instead — POST " +
                                                "`{ id, message: { raw } }` carrying the full message — so the " +
                                                "recipients ride in the request. Those To/Cc/Bcc addresses must then " +
                                                "all be on this deployment's outbound allowlist (the " +
                                                "OUTBOUND_RECIPIENT_ALLOWLIST var; unset means every send is denied), " +
                                                "written as a bare addr@host or Name <addr@host> with no quotes or " +
                                                "comments, and more than 25 of them needs interactive approval." },
  "gmail.users.messages.import":           { decision: "elicit", category: "external_data_flow" },
  "gmail.users.messages.delete":           { decision: "elicit", category: "irreversible" },
  "gmail.users.messages.batchDelete":      { decision: "elicit", category: "bulk_destructive",
                                              reasoning: "Bulk irreversible delete; needs human confirmation when elicitation lands" },
  "gmail.users.threads.delete":            { decision: "elicit", category: "irreversible" },

  // === Tier 3: always deny ===
  "gmail.users.settings.delegates.list":           { decision: "deny", category: "capability_escalation",
                                                      reasoning: "Enumerates accounts authorised to send/receive as the user; recon for delegation abuse and out of scope for read-mail / send-mail use cases." },
  "gmail.users.settings.delegates.get":            { decision: "deny", category: "capability_escalation",
                                                      reasoning: "Reads a specific delegation. Same recon concern as delegates.list." },
  "gmail.users.settings.delegates.create":         { decision: "deny", category: "capability_escalation",
                                                      reasoning: "Persistent forwarding survives token revocation" },
  "gmail.users.settings.delegates.delete":         { decision: "deny", category: "capability_escalation",
                                                      reasoning: "Removes persistent account-access delegation; symmetric with delegates.create at Tier-3." },
  "gmail.users.settings.forwardingAddresses.create": { decision: "deny", category: "capability_escalation",
                                                      reasoning: "Configures persistent off-account inbound-mail forwarding; survives token revocation, classic exfiltration channel." },
  "gmail.users.settings.forwardingAddresses.delete": { decision: "deny", category: "capability_escalation",
                                                      reasoning: "Removes persistent forwarding configuration; symmetric with .create at Tier-3." },
  "gmail.users.settings.filters.create":           { decision: "allow", inspect: inspectFilterCreate,
                                                      clientNote:
                                                        "The filter's `action` block is checked: a non-empty `forward` or " +
                                                        "`forwardingEmail` STRING is denied (`forward: true` is not forwarding). " +
                                                        "`addLabelIds` with \"TRASH\" or \"SPAM\", or `removeLabelIds` with \"INBOX\" " +
                                                        "(auto-archive), needs interactive approval. A body with no `action` object, or " +
                                                        "an `action` key other than addLabelIds, removeLabelIds, forward (or their " +
                                                        "snake_case forms), is " +
                                                        "denied. Other label-only actions pass." },
  "gmail.users.settings.filters.delete":           { decision: "deny", category: "persistent_state",
                                                      reasoning: "Removes user-defined filter rules; could undo legitimate spam/security filtering set by the user." },
  "gmail.users.settings.sendAs.create":            { decision: "deny", category: "capability_escalation",
    reasoning: "Unreachable as deployed, so denied rather than annotated: it needs the gmail.settings.sharing scope, which is intentionally not in gmailProvider.oauth.scopes, so it 403s upstream whatever an inspector decides. Denying also makes it symmetric with sendAs.update/patch/delete, already Tier-3.\n" +
      "RE-ENABLEMENT PATH (kept cheap on purpose — `inspectSendAsCreate` and its tests in __tests__/surface-review-sendas*.test.ts are retained as the reference implementation of the inspector pattern, and are still exercised directly): add https://www.googleapis.com/auth/gmail.settings.sharing to gmailProvider.oauth.scopes, re-deploy, AND restore `inspect: inspectSendAsCreate` on this entry — the decision must go back to `allow` for the inspector to run at all, since a static deny short-circuits before `inspect` is read.\n" +
      "What that inspector enforces, and why it is worth keeping: `sendAsEmail` must be on the deployment's outbound allowlist (OUTBOUND_RECIPIENT_ALLOWLIST; unset means an empty list, so every call denies), a body without it is denied, and `inspectSmtpMsa` rejects any `smtpMsa` sub-object whose host is not on the empty-by-default `SMTP_MSA_HOST_ALLOWLIST` (in `inspectors/smtp-msa-allowlist.ts`) — so in practice any `smtpMsa` block is refused." },
  "gmail.users.settings.sendAs.update":            { decision: "deny", category: "capability_escalation",
                                                      reasoning: "Modifies persistent send-as identity (display name, signature, reply-to). The create-time inspector enforces user-email identity; an update path circumvents that — simpler/safer to deny." },
  "gmail.users.settings.sendAs.patch":             { decision: "deny", category: "capability_escalation",
                                                      reasoning: "Same surface as sendAs.update, partial-update flavour. Same identity-spoofing concern; deny rather than wire a second inspector." },
  "gmail.users.settings.sendAs.delete":            { decision: "deny", category: "capability_escalation",
                                                      reasoning: "Removes a persistent send-as identity; symmetric with sendAs.create at Tier-3." },
  "gmail.users.settings.sendAs.smimeInfo.insert":  { decision: "deny", category: "capability_escalation",
                                                      reasoning: "Installs an S/MIME signing certificate for a send-as identity; lets the agent send cryptographically-signed mail under the user's name." },

  // ===========================================================================
  // Google Calendar v3 — "read + event management" surface.
  // Reached on the same www.googleapis.com origin as Gmail (apiBaseUrl), under
  // /calendar/v3/. Sharing (acl.*) and calendar lifecycle are denied; event
  // writes that can email invitations are gated by inspectEventAttendees.
  // ===========================================================================

  // --- Reads ---
  "calendar.calendarList.list":            { decision: "allow", category: "standard_read" },
  "calendar.calendarList.get":             { decision: "allow", category: "standard_read" },
  "calendar.calendars.get":                { decision: "allow", category: "standard_read" },
  "calendar.events.list":                  { decision: "allow", category: "standard_read" },
  "calendar.events.get":                   { decision: "allow", category: "standard_read" },
  "calendar.events.instances":             { decision: "allow", category: "standard_read" },
  "calendar.freebusy.query":               { decision: "allow", category: "standard_read",
                                              reasoning: "POST-shaped read: returns busy intervals for the queried calendars; no state change." },
  "calendar.colors.get":                   { decision: "allow", category: "standard_read" },
  "calendar.settings.get":                 { decision: "allow", category: "standard_read" },
  "calendar.settings.list":                { decision: "allow", category: "standard_read" },

  // --- Event writes (attendee allowlist enforced) ---
  "calendar.events.insert":                { decision: "allow", inspect: inspectEventAttendees,
                                              clientNote: ATTENDEE_NOTE },
  "calendar.events.update":                { decision: "allow", inspect: inspectEventAttendees,
                                              clientNote: ATTENDEE_NOTE },
  "calendar.events.patch":                 { decision: "allow", inspect: inspectEventAttendees,
                                              clientNote: ATTENDEE_NOTE },

  // --- Event writes that can't introduce arbitrary attendees ---
  "calendar.events.move":                  { decision: "allow", category: "standard_write",
                                              reasoning: "Moves an event between the user's own calendars (destination query param); no attendee mutation, so no outbound-invite inspector." },
  "calendar.events.quickAdd":              { decision: "allow", category: "standard_write",
                                              reasoning: "Natural-language `text` query param parsed into title/time; cannot set structured attendees, so no outbound-invite inspector." },

  // --- Elicit: external data in / irreversible ---
  "calendar.events.import":                { decision: "elicit", category: "external_data_flow",
                                              inspect: inspectEventAttendees,
                                              clientNote: ATTENDEE_NOTE_IMPORT },
  "calendar.events.delete":                { decision: "elicit", category: "irreversible" },

  // --- Tier 3: always deny ---
  "calendar.acl.list":                     { decision: "deny", category: "capability_escalation",
                                              reasoning: "Enumerates who a calendar is shared with; recon for sharing abuse. Same concern as gmail delegates.list." },
  "calendar.acl.get":                      { decision: "deny", category: "capability_escalation",
                                              reasoning: "Reads a specific sharing rule; same recon concern as acl.list." },
  "calendar.acl.insert":                   { decision: "deny", category: "capability_escalation",
                                              reasoning: "Grants another principal access to a calendar; persistent delegation that survives token revocation — the direct analog to gmail delegates/forwarding.create." },
  "calendar.acl.update":                   { decision: "deny", category: "capability_escalation",
                                              reasoning: "Modifies a persistent calendar-sharing grant; same escalation concern as acl.insert." },
  "calendar.acl.patch":                    { decision: "deny", category: "capability_escalation",
                                              reasoning: "Partial-update flavour of acl.update; same persistent-sharing escalation concern." },
  "calendar.acl.delete":                   { decision: "deny", category: "capability_escalation",
                                              reasoning: "Removes a calendar-sharing grant; symmetric with acl.insert at Tier-3." },
  "calendar.acl.watch":                    { decision: "deny", category: "capability_escalation",
                                              reasoning: "Opens a push-notification channel over the sharing-rule collection; out of scope and exposes the sharing graph." },
  "calendar.calendars.delete":             { decision: "deny", category: "irreversible",
                                              reasoning: "Permanently deletes an entire calendar and all its events; destructive and outside the read+event-management surface." },
  "calendar.calendars.clear":              { decision: "deny", category: "bulk_destructive",
                                              reasoning: "Deletes ALL events on the primary calendar in one call; bulk-irreversible and outside the read+event-management surface." },

  // any operation NOT listed here is implicitly denied (incl. calendars
  // insert/update/patch, calendarList insert/delete/update/patch, all *.watch,
  // and channels.stop)
} as const;
