import type { SurfaceReview } from "@local/shared";
import { inspectInvoiceDraft, inspectCreditNoteDraft } from "./inspectors/drafts.js";
import { inspectBankTxCreate } from "./inspectors/bank-transactions.js";

import specJson from "./spec.json" with { type: "json" };

interface SpecLike {
  paths: Record<string, Record<string, { operationId?: string }>>;
}

// HTTP method keys we recognise on a path-item; everything else (e.g. "parameters") is skipped.
const HTTP_METHODS = new Set(["get", "put", "post", "delete", "options", "head", "patch", "trace"]);

function buildReadAllows(): Record<string, { decision: "allow"; category: "standard_read" }> {
  const out: Record<string, { decision: "allow"; category: "standard_read" }> = {};
  for (const [, methods] of Object.entries((specJson as SpecLike).paths)) {
    const get = methods["get"];
    if (get && typeof get.operationId === "string") {
      const id = get.operationId;
      if (id.startsWith("xero.accounting.") || id.startsWith("xero.files.") || id.startsWith("xero.payroll.au.")) {
        out[id] = { decision: "allow", category: "standard_read" };
      }
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// clientNote prose. Client-visible, aimed at the model, appended to the
// operation's spec description by annotateSpecWithSurfaceReview. Each note
// states only what its inspector actually enforces (see ./inspectors/); the
// structural facts ("allowed but inspected") are generated by the annotator.
// ---------------------------------------------------------------------------

/** makeDraftStatusInspector — same policy for invoices and credit notes, with
 *  the resource's own array wrapper, id field and article substituted in.
 *  `article` is explicit because "a invoice" is what interpolation produces. */
const draftStatusNote = (arrayKey: string, idField: string, article: string, label: string): string =>
  `Each item in \`${arrayKey}\` (or the flat by-id body) is status-gated: \`Status\` must be ` +
  `"DRAFT" or "SUBMITTED"; ANY other value is denied, including the AUTHORISED/VOIDED/DELETED ` +
  `transitions that are Xero's only way to post, void or delete ${article} ${label} — so none ` +
  `of those is possible here. \`Status\` may be omitted only if the item carries ` +
  `\`${idField}\` (read from the body, not the path); otherwise the create is denied as ` +
  `implicitly AUTHORISED. \`SentToContact: true\` is denied — it emails the ${label} to the ` +
  `contact. An empty payload is denied.`;

// Not inspector conditions: these reads are gated on scopes this deployment
// does not hold, so they fail before any policy applies. NB `/Journals` is the
// general-ledger journal-lines feed, NOT ManualJournals — the latter's scope
// (accounting.manualjournals.read) IS granted and getManualJournals works.
//
// The rule applied here is NOT "every scope the op accepts is ungranted" — that
// flags 83 surface entries, essentially all false positives, because the
// bundled spec still declares the deprecated coarse families
// (accounting.transactions.read, accounting.settings.read, …) that index.ts
// deliberately replaced with granular scopes. A full audit would need a
// coarse→granular mapping table that does not exist in this repo, and guessing
// at it is worse than not auditing.
//
// The rule that IS applied: every scope the operation accepts is ungranted AND
// none of them is a deprecated coarse family with a granted granular
// replacement. That is mechanically checkable (see client-notes.test.ts, which
// recomputes it) and yields the five entries below.
const JOURNALS_SCOPE_NOTE =
  "Unreachable as deployed: `/Journals` is the general-ledger journal-lines feed and needs " +
  "the `accounting.journals.read` scope, which this server does not request (Xero rejects it " +
  "as invalid_scope for this client_id), so the call fails upstream with 403. This does NOT " +
  "affect ManualJournals — `getManualJournals` is available and is the right endpoint for " +
  "manual journal entries. For posted activity use the reports or bank-transaction endpoints.";

/** Payroll WRITE scopes are not requested — only the `.read` halves are. These
 *  four are elicit-gated, so without this note the client is told to seek
 *  approval for a call the token could never make. */
const payrollWriteScopeNote = (scope: string, what: string): string =>
  `Unreachable as deployed: writing ${what} needs the \`${scope}\` scope; this server requests ` +
  `only \`${scope}.read\`, so the call fails upstream with 403 — before and regardless of any ` +
  "approval. Read the payroll data instead, and tell the user this deployment cannot write it.";

const PAYMENT_SERVICES_SCOPE_NOTE =
  "Unreachable as deployed: this read needs the `paymentservices` scope, which this server " +
  "does not request, so the call fails upstream with 403. Note the write side is denied by " +
  "surface review outright — this read is not the usable half of a usable pair.";

// Judgement call, not mechanically derived: this operation accepts the coarse
// `accounting.reports.read` (ungranted) or the granular
// `accounting.reports.tenninetynine.read` (also ungranted). Eight OTHER granular
// accounting.reports.*.read scopes ARE granted, but each covers a different
// report, so none supersedes this one. Flagged on that reading; if Xero ever
// treats a granted report scope as covering 1099, this note becomes wrong.
const TEN_NINETY_NINE_SCOPE_NOTE =
  "Unreachable as deployed: this report needs `accounting.reports.tenninetynine.read` (or the " +
  "deprecated coarse `accounting.reports.read`); this server grants neither — the eight " +
  "granular report scopes it does hold each cover a different report. The call fails " +
  "upstream with 403.";

/** inspectBankTxCreate — shared by createBankTransactions and updateBankTransaction. */
const BANK_TX_NOTE =
  "Requires a non-empty `BankTransactions` array (the by-id update takes the same wrapper). " +
  '`Type` must be "SPEND" or "RECEIVE"; ANY other value is denied. `Status`, if given, must ' +
  'be "AUTHORISED" — omitting it is fine (Xero defaults to it), but ANY other value is ' +
  "denied, including the DELETED/VOIDED transitions that are the only way to delete or void " +
  "a bank transaction. `IsReconciled: true` is denied — reconciliation comes from real " +
  "bank-statement matching and must not be forged.";

const TIER_1_ALLOW_INSPECT_OR_BARE: SurfaceReview = {
  "xero.accounting.createInvoices":              { decision: "allow", inspect: inspectInvoiceDraft,
                                                    clientNote: draftStatusNote("Invoices", "InvoiceID", "an", "invoice") },
  "xero.accounting.updateOrCreateInvoices":      { decision: "allow", inspect: inspectInvoiceDraft,
                                                    clientNote: draftStatusNote("Invoices", "InvoiceID", "an", "invoice") },
  // updateInvoice (singular, by ID) shares the inspector. Xero has no separate
  // delete/void operation — voiding/deleting flows through this endpoint by
  // setting Status to VOIDED/DELETED, which the inspector denies (only allows
  // Status ∈ {DRAFT, SUBMITTED}).
  "xero.accounting.updateInvoice":               { decision: "allow", inspect: inspectInvoiceDraft,
                                                    clientNote: draftStatusNote("Invoices", "InvoiceID", "an", "invoice") },
  // Credit notes mirror invoices exactly: bulk PUT/POST send { CreditNotes: [...] },
  // singular updateCreditNote (by ID) sends a flat object. Same Status lifecycle, so
  // the shared draft inspector gates them — only DRAFT/SUBMITTED (or a Status-omitted
  // update carrying CreditNoteID) is allowed; AUTHORISED/PAID/VOIDED/DELETED are denied
  // with a clear message. Xero has no separate delete/void op; that flows through these.
  "xero.accounting.createCreditNotes":           { decision: "allow", inspect: inspectCreditNoteDraft,
                                                    clientNote: draftStatusNote("CreditNotes", "CreditNoteID", "a", "credit note") },
  "xero.accounting.updateOrCreateCreditNotes":   { decision: "allow", inspect: inspectCreditNoteDraft,
                                                    clientNote: draftStatusNote("CreditNotes", "CreditNoteID", "a", "credit note") },
  "xero.accounting.updateCreditNote":            { decision: "allow", inspect: inspectCreditNoteDraft,
                                                    clientNote: draftStatusNote("CreditNotes", "CreditNoteID", "a", "credit note") },
  "xero.accounting.createContacts":              { decision: "allow", category: "standard_write" },
  "xero.accounting.updateOrCreateContacts":      { decision: "allow", category: "standard_write" },
  "xero.accounting.createRepeatingInvoices":         { decision: "allow", category: "standard_write" },
  "xero.accounting.updateRepeatingInvoice":          { decision: "allow", category: "standard_write" },
  "xero.accounting.updateOrCreateRepeatingInvoices": { decision: "allow", category: "standard_write" },
  "xero.accounting.createBankTransactions":      { decision: "allow", inspect: inspectBankTxCreate,
                                                    clientNote: BANK_TX_NOTE },
  "xero.accounting.updateBankTransaction":       { decision: "allow", inspect: inspectBankTxCreate,
                                                    clientNote: BANK_TX_NOTE },
  // Attachment uploads are bare allows: the inspector relied on contentType/rawBody,
  // which the request-handler does not currently surface to inspectors (only body+query
  // are passed). Re-wire the inspector once the handler forwards request bytes.
  "xero.accounting.createInvoiceAttachmentByFileName":      { decision: "allow", category: "standard_write" },
  "xero.accounting.updateInvoiceAttachmentByFileName":      { decision: "allow", category: "standard_write" },
  "xero.accounting.createCreditNoteAttachmentByFileName":   { decision: "allow", category: "standard_write" },
  "xero.accounting.updateCreditNoteAttachmentByFileName":   { decision: "allow", category: "standard_write" },
  "xero.files.uploadFile":                       { decision: "allow", category: "standard_write" },
  "xero.files.createFolder":                     { decision: "allow", category: "standard_write" },
};

// Tier-2 (elicit): short-circuits to deny in slice 2 (live elicitation lands in slice 3).
// Listed explicitly so audit logs say `decision=elicit elicitationOutcome=unsupported reason=<op>`
// rather than the vaguer "operation not in surface review".
//
// NB: The plan's original list referenced operationIds that don't exist in the actual Xero spec —
// `deleteInvoice`/`voidInvoice`/`deleteContact`/`deleteBankTransaction`/`createEmployees` (plural).
// Xero handles those mutations through Update operations on the same resources. Removed from
// this list. Substituted: createBatchPayment (singular, real id) and createEmployee (singular).
const TIER_2_ELICIT: SurfaceReview = {
  "xero.accounting.emailInvoice":                { decision: "elicit", category: "external_data_flow" },
  "xero.accounting.createBatchPayment":          { decision: "elicit", category: "financial_legal" },
  "xero.payroll.au.createEmployee":              { decision: "elicit", category: "persistent_state",
                                                    clientNote: payrollWriteScopeNote("payroll.employees", "employees") },
  "xero.payroll.au.updateEmployee":              { decision: "elicit", category: "persistent_state",
                                                    clientNote: payrollWriteScopeNote("payroll.employees", "employees") },
  "xero.payroll.au.createPayRun":                { decision: "elicit", category: "financial_legal",
                                                    clientNote: payrollWriteScopeNote("payroll.payruns", "pay runs") },
  "xero.payroll.au.updatePayRun":                { decision: "elicit", category: "financial_legal",
                                                    clientNote: payrollWriteScopeNote("payroll.payruns", "pay runs") },
};

// Tier-3 (deny): capability-escalation; never elicit-able.
// Reduced from plan: createUsers/deleteUsers/archiveTrackingCategory/deleteTaxRate/updateOrganisation/
// deletePayrollCalendar/updatePaymentService/deletePaymentService/updateSettings — all DOM-checked,
// none exist as operationIds in the merged Xero spec. createPaymentService moved from payroll.au
// to accounting (where it actually lives).
const TIER_3_DENY: SurfaceReview = {
  "xero.accounting.deleteTrackingCategory":      { decision: "deny", category: "irreversible",
                                                     reasoning: "Tracking-category deletion cascades through historic transactions; manual undo only." },
  "xero.accounting.updateTaxRate":               { decision: "deny", category: "irreversible",
                                                     reasoning: "Tax-rate updates trigger Xero-side recalculation of historic transactions." },
  "xero.accounting.deleteAccount":               { decision: "deny", category: "irreversible",
                                                     reasoning: "Chart-of-accounts deletion cascades; manual undo only." },
  "xero.accounting.createPaymentService":        { decision: "deny", category: "capability_escalation",
                                                     reasoning: "Payment services configure outbound bank rails; not elicit-recoverable." },
  "xero.accounting.createBrandingThemePaymentServices": { decision: "deny", category: "capability_escalation",
                                                     reasoning: "Linking a payment service to a branding theme exposes outbound bank rails on customer-facing invoices; not elicit-recoverable." },
};

// Reads that `buildReadAllows()` allows but the granted scopes cannot reach, so
// they 403 upstream no matter what the surface review says. Kept as `allow`
// (the review's verdict is unchanged; it is the token that is short) with a
// clientNote so a client does not plan around an endpoint that cannot answer.
// See the rule stated above the note constants for which ops qualify and why a
// full scope audit is deliberately not attempted.
const SCOPE_UNREACHABLE_READS: SurfaceReview = {
  "xero.accounting.getJournals":        { decision: "allow", category: "standard_read", clientNote: JOURNALS_SCOPE_NOTE },
  "xero.accounting.getJournal":         { decision: "allow", category: "standard_read", clientNote: JOURNALS_SCOPE_NOTE },
  "xero.accounting.getJournalByNumber": { decision: "allow", category: "standard_read", clientNote: JOURNALS_SCOPE_NOTE },
  "xero.accounting.getPaymentServices": { decision: "allow", category: "standard_read", clientNote: PAYMENT_SERVICES_SCOPE_NOTE },
  "xero.accounting.getBrandingThemePaymentServices":
                                        { decision: "allow", category: "standard_read", clientNote: PAYMENT_SERVICES_SCOPE_NOTE },
  "xero.accounting.getReportTenNinetyNine":
                                        { decision: "allow", category: "standard_read", clientNote: TEN_NINETY_NINE_SCOPE_NOTE },
};

export const surfaceReview: SurfaceReview = Object.freeze({
  ...buildReadAllows(),
  ...TIER_1_ALLOW_INSPECT_OR_BARE,
  ...TIER_2_ELICIT,
  ...TIER_3_DENY,
  // Last: overrides the bare allow that buildReadAllows() generated for these.
  ...SCOPE_UNREACHABLE_READS,
});
